---

:verbose: false
:concurrency: 5

:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    HeartbeatJob:
      every: ["5m", first_in: "0s"]
    SubscriptionPlacementJob:
      every: "5m"
    SubscriptionConfirmJob:
      every: "5m"
    OrderCycleOpenedJob:
      every: "5m"
    OrderCycleClosingJob:
      every: "5m"
    # Don't Waste Surplus Module Jobs
    Surplus::ExpireListingsJob:
      every: "5m"
    Surplus::ExpireReservationsJob:
      every: "5m"
    Surplus::ExpireOffersJob:
      every: "15m"
